### ISSUE TITLE
No contract or not a valid smart contract

### ISSUE THREAD

**Issue by li-jian-feng** [Fenguoz/tron-php#15]
```
PHP Fatal error:  Uncaught Tron\Exceptions\TransactionException: No contract or not a valid smart contract in /data/wwwroot/tron/vendor/fenguoz/tron-php/src/TRC20.php:82
Stack trace:
#0 /data/wwwroot/tron/20.php(93): Tron\TRC20->transfer()
#1 /data/wwwroot/tron/20.php(125): TRC20Test->testTransfer()

```

请问是什么原因啊

**Comment by Fenguoz** [comment]
检查是否合约地址错误
